spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  data:
    rest:
      base-path: /api
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    root: DEBUG